CONFIG_NAME: 'ManiGAN'

DATASET_NAME: 'FiveK'
DATA_DIR: '../data/FiveK_for_zip'
GPU_ID: '0'
WORKERS: 4

# add by jwt
ANNO_PATH: '../data/FiveK_for_zip/FiveK.json'
LABEL_DIR: ''
IMAGE_DIR: '../data/FiveK_for_zip/images'
FiveK: True

TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    NET_G: ''
    NET_C: ''
    NET_D: ''
    B_NET_D: True
    BATCH_SIZE: 32 
    MAX_EPOCH: 600
    SNAPSHOT_INTERVAL: 5
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    #
    NET_E: ''
    W_GAN: 0.0
    W_L1: 2.0
    W_VGG: 0.1
    W_KL: 1.0

    SMOOTH:
        GAMMA1: 4.0  
        GAMMA2: 5.0
        GAMMA3: 10.0  
        LAMBDA: 5.0


GAN:
    DF_DIM: 64
    GF_DIM: 32
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
    WORDS_NUM: 18
